import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/theme_provider.dart';
import '../../providers/transaction_provider.dart';
import '../../providers/budget_provider.dart';
import '../../widgets/mascot/mascot_widget.dart';
import '../../widgets/charts/budget_progress_card.dart';
import '../../models/transaction.dart';
import '../../models/budget.dart';
